//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taLib
    {
        public int LID { get; set; }
        public Nullable<int> LParent { get; set; }
        public Nullable<int> LConcept { get; set; }
        public string LCode { get; set; }
        public string LName { get; set; }
        public string LName1 { get; set; }
        public string LName2 { get; set; }
        public Nullable<int> LID1 { get; set; }
        public Nullable<int> LID2 { get; set; }
        public Nullable<int> LID3 { get; set; }
        public Nullable<int> LID4 { get; set; }
        public Nullable<int> LID5 { get; set; }
        public Nullable<int> LInt1 { get; set; }
        public Nullable<int> LInt2 { get; set; }
        public Nullable<System.DateTime> LDate1 { get; set; }
        public Nullable<System.DateTime> LDate2 { get; set; }
        public Nullable<double> LNum1 { get; set; }
        public Nullable<double> LNum2 { get; set; }
        public Nullable<long> LBInt1 { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> LDate3 { get; set; }
    }
}
