//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAmortization
    {
        public int ID { get; set; }
        public int SecurityID { get; set; }
        public System.DateTime ADate { get; set; }
        public Nullable<double> Nominal { get; set; }
        public double Value { get; set; }
    }
}
