//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tConseil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tConseil()
        {
            this.tConseilHoraire = new HashSet<tConseilHoraire>();
        }
    
        public int ID { get; set; }
        public string Violation { get; set; }
        public string Conseil { get; set; }
        public Nullable<System.DateTime> Terme { get; set; }
        public Nullable<System.DateTime> Prolongation { get; set; }
        public string Possesseur { get; set; }
        public string Commentaire { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> PrononceDate { get; set; }
        public Nullable<int> Priorite { get; set; }
        public Nullable<System.DateTime> ExecDate { get; set; }
        public Nullable<decimal> MinNomRiskPrice { get; set; }
        public Nullable<decimal> MaxNomRiskPrice { get; set; }
        public Nullable<int> InstOwnerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tConseilHoraire> tConseilHoraire { get; set; }
    }
}
