//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEDO
    {
        public int ID { get; set; }
        public string EDO { get; set; }
        public string Crypto { get; set; }
        public string Publisher { get; set; }
        public string FIO_owner { get; set; }
        public System.DateTime Srok { get; set; }
        public string Department { get; set; }
        public string FIO_resp { get; set; }
        public Nullable<System.DateTime> DateCancel { get; set; }
        public string Storage { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string EmailTo { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string UserName { get; set; }
        public string FileName { get; set; }
    }
}
