//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEnvoiHoraire
    {
        public int ID { get; set; }
        public int EnvoiID { get; set; }
        public int EnvoiHoraireTypeID { get; set; }
        public int ModeID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public string Comment { get; set; }
    
        public virtual tEnvoiHoraireType tEnvoiHoraireType { get; set; }
        public virtual tEnvoi tEnvoi { get; set; }
    }
}
