//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInvestDeclLink
    {
        public int InvestDeclLinkID { get; set; }
        public Nullable<int> InvestDeclID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<bool> Enb { get; set; }
        public Nullable<int> ObjID { get; set; }
        public Nullable<int> ObjType { get; set; }
    
        public virtual tInvestDecl tInvestDecl { get; set; }
    }
}
