//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInvestDeclWhere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tInvestDeclWhere()
        {
            this.tInvestDeclSec = new HashSet<tInvestDeclSec>();
        }
    
        public int InvestDeclWhereID { get; set; }
        public Nullable<int> InvestDeclID { get; set; }
        public Nullable<bool> Enb { get; set; }
        public string NameWhere { get; set; }
        public Nullable<double> StartValue { get; set; }
        public Nullable<double> StopValue { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Create_UserID { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Modify_UserID { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> FLAG_Calculation { get; set; }
        public Nullable<int> FLAG_Method_1 { get; set; }
        public Nullable<int> FLAG_Method_2 { get; set; }
        public Nullable<int> FLAG_Group { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> FLAG_Long { get; set; }
        public Nullable<int> PeriodDay { get; set; }
        public Nullable<double> PeriodDRB { get; set; }
        public Nullable<int> FLAG_Type { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
    
        public virtual tInvestDecl tInvestDecl { get; set; }
        public virtual tInvestDeclGroupType tInvestDeclGroupType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tInvestDeclSec> tInvestDeclSec { get; set; }
    }
}
