//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLimitList
    {
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> EmitentID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public Nullable<decimal> Value4 { get; set; }
        public Nullable<decimal> Value5 { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    
        public virtual tFinInst tFinInst { get; set; }
    }
}
