//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tModDeal
    {
        public int ModDealID { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public Nullable<int> SecurityID { get; set; }
        public Nullable<int> PortfolioID { get; set; }
        public Nullable<int> FinInstID { get; set; }
        public Nullable<int> TreatyID { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<byte> Direction { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<double> DealPrice { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> AccInt { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> DealTypeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tFinInst tFinInst { get; set; }
        public virtual tSecurity tFund { get; set; }
        public virtual tPortfolio tPortfolio { get; set; }
        public virtual tSecurity tSecurity { get; set; }
        public virtual tTreaty tTreaty { get; set; }
    }
}
