//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tObjClsRelation
    {
        public int ObjClsRelationID { get; set; }
        public int ObjClassifierID { get; set; }
        public int ObjType { get; set; }
        public int ObjectID { get; set; }
        public System.DateTime OnDate { get; set; }
        public double Value { get; set; }
        public string Comment { get; set; }
        public System.DateTime InDateTime { get; set; }
        public string UserName { get; set; }
    }
}
