//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tObjClassifier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tObjClassifier()
        {
            this.tEnvoi = new HashSet<tEnvoi>();
            this.tRegDoc = new HashSet<tRegDoc>();
            this.tReestr = new HashSet<tReestr>();
            this.tEnregistrement = new HashSet<tEnregistrement>();
            this.tEnregistrement1 = new HashSet<tEnregistrement>();
            this.tEnregDTSteps = new HashSet<tEnregDTSteps>();
        }
    
        public int ObjClassifierID { get; set; }
        public int ParentID { get; set; }
        public int ObjType { get; set; }
        public string Name { get; set; }
        public string NameBrief { get; set; }
        public int UniqueFlag { get; set; }
        public int RequiredFlag { get; set; }
        public int OnDateFlag { get; set; }
        public string Comment { get; set; }
        public System.DateTime InDateTime { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEnvoi> tEnvoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRegDoc> tRegDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReestr> tReestr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEnregistrement> tEnregistrement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEnregistrement> tEnregistrement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEnregDTSteps> tEnregDTSteps { get; set; }
    }
}
