//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tODRests
    {
        public int ID { get; set; }
        public Nullable<int> BalAccID { get; set; }
        public Nullable<int> Reg1ID { get; set; }
        public Nullable<int> Reg2ID { get; set; }
        public Nullable<int> Reg3ID { get; set; }
        public Nullable<int> Reg4ID { get; set; }
        public Nullable<int> Reg5ID { get; set; }
        public Nullable<int> Reg6ID { get; set; }
        public Nullable<int> ValueID { get; set; }
    }
}
