//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPayment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Number { get; set; }
        public string BICI { get; set; }
        public string RAccI { get; set; }
        public string BankI { get; set; }
        public string KAccI { get; set; }
        public string INNI { get; set; }
        public string KPPI { get; set; }
        public string NameI { get; set; }
        public string BICO { get; set; }
        public string RAccO { get; set; }
        public string BankO { get; set; }
        public string KAccO { get; set; }
        public string INNO { get; set; }
        public string KPPO { get; set; }
        public string NameO { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Queue { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
