//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPortfolioTreaty
    {
        public int ID { get; set; }
        public Nullable<int> PortfolioID { get; set; }
        public Nullable<int> TreatyID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    
        public virtual tPortfolio tPortfolio { get; set; }
        public virtual tTreaty tTreaty { get; set; }
    }
}
