//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPortfolio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPortfolio()
        {
            this.tPortfolioTreaty = new HashSet<tPortfolioTreaty>();
            this.tModDeal = new HashSet<tModDeal>();
        }
    
        public int PortfolioID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PortfolioTypeID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ExternalID { get; set; }
    
        public virtual tPortfolioType tPortfolioType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPortfolioTreaty> tPortfolioTreaty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tModDeal> tModDeal { get; set; }
    }
}
