//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQuikRate
    {
        public int ID { get; set; }
        public System.DateTime DateRate { get; set; }
        public Nullable<System.DateTime> TimeRate { get; set; }
        public string Instrument { get; set; }
        public string Brief { get; set; }
        public string Name { get; set; }
        public string ISIN { get; set; }
        public string RegNumber { get; set; }
        public string ClassCode { get; set; }
        public Nullable<int> Lot { get; set; }
        public Nullable<double> Last { get; set; }
        public Nullable<double> Avg { get; set; }
        public Nullable<double> Bid { get; set; }
        public Nullable<double> NKD { get; set; }
        public Nullable<double> Nominal { get; set; }
        public string Val { get; set; }
    }
}
