//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQuikLimits
    {
        public int ID { get; set; }
        public string Curr { get; set; }
        public string Client { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
