//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQUIK_UK_Deal
    {
        public int ID { get; set; }
        public long DealNumber { get; set; }
        public long OrderNumber { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public System.DateTime DealTime { get; set; }
        public string DealType { get; set; }
        public string InstrumentBrief { get; set; }
        public string InstrumentCode { get; set; }
        public string Operation { get; set; }
        public double DealPrice { get; set; }
        public Nullable<double> DealPriceRepoClose { get; set; }
        public int Quantity { get; set; }
        public string ClientCode { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Capacity { get; set; }
        public Nullable<double> CommissionTS { get; set; }
        public Nullable<double> Yield { get; set; }
        public Nullable<double> NKD { get; set; }
        public Nullable<double> REPOVolume { get; set; }
        public Nullable<double> REPOSum { get; set; }
        public Nullable<int> REPOSrok { get; set; }
        public Nullable<double> REPOStavka { get; set; }
        public Nullable<double> REPOYield { get; set; }
        public Nullable<byte> IsProcessed { get; set; }
        public Nullable<System.DateTime> DTProcessed { get; set; }
        public string Partner { get; set; }
        public string OrgPartner { get; set; }
        public string SecurityBrief { get; set; }
        public Nullable<double> InitDiscount { get; set; }
        public Nullable<double> LowDiscount { get; set; }
        public Nullable<double> HiDiscount { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string Valuta { get; set; }
        public string ValutaRasch { get; set; }
        public Nullable<System.DateTime> DateRasch { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string ISIN { get; set; }
        public string CodeClass { get; set; }
        public Nullable<int> UID { get; set; }
    }
}
