//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQuikDeal
    {
        public int ID { get; set; }
        public string Brief { get; set; }
        public string Name { get; set; }
        public string ISIN { get; set; }
        public string RegNumber { get; set; }
        public Nullable<int> SecurityID { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<double> DealPrice { get; set; }
        public Nullable<byte> Direction { get; set; }
        public Nullable<System.DateTime> DateDeal { get; set; }
        public string ClientCode { get; set; }
        public string ClientAccount { get; set; }
        public string ClassCode { get; set; }
        public Nullable<int> Lot { get; set; }
        public Nullable<int> Trans_ID { get; set; }
        public Nullable<int> TypeO { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> Type { get; set; }
        public Nullable<int> TreatyID { get; set; }
        public Nullable<long> OrderNum { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ReplayCode { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> QuikID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<byte> Form { get; set; }
    
        public virtual tQuik tQuik { get; set; }
        public virtual tQuikDealStatus tQuikDealStatus { get; set; }
        public virtual tQuikDealType tQuikDealType { get; set; }
        public virtual tSecurity tSecurity { get; set; }
        public virtual tTreaty tTreaty { get; set; }
    }
}
