//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRate
    {
        public int RateID { get; set; }
        public int TradeSystemID { get; set; }
        public int SecurityID { get; set; }
        public int FundID { get; set; }
        public System.DateTime RateDate { get; set; }
        public Nullable<double> CourseBid { get; set; }
        public Nullable<double> CourseOffer { get; set; }
        public Nullable<double> CourseCurrent { get; set; }
        public Nullable<double> CourseOpen { get; set; }
        public Nullable<double> CourseClose { get; set; }
        public Nullable<double> CourseMin { get; set; }
        public Nullable<double> CourseMax { get; set; }
        public Nullable<double> CourseAvg { get; set; }
        public Nullable<double> AccInt { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
