//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReestr
    {
        public int ID { get; set; }
        public Nullable<int> InstOwnerID { get; set; }
        public string Nomer { get; set; }
        public System.DateTime DateR { get; set; }
        public int StatusID { get; set; }
        public string Theme { get; set; }
        public string EmailTo { get; set; }
        public string FileName { get; set; }
        public System.DateTime InDateTime { get; set; }
    
        public virtual tObjClassifier tObjClassifier { get; set; }
    }
}
