//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRegDoc
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> ODate { get; set; }
        public string RegNum { get; set; }
        public string Theme { get; set; }
        public string Resolution { get; set; }
        public string Directed { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public string ANum { get; set; }
        public string FileNameI { get; set; }
        public string FileNameO { get; set; }
        public string LotusLinkI { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<bool> IsAcquaintance { get; set; }
        public Nullable<bool> IsComplaint { get; set; }
        public Nullable<int> InstOwnerID { get; set; }
        public bool Direction { get; set; }
        public Nullable<int> ContrID { get; set; }
        public Nullable<int> OrigUserID { get; set; }
        public Nullable<bool> IsComplaintN { get; set; }
        public Nullable<bool> IsClientP { get; set; }
    
        public virtual tObjClassifier tObjClassifier { get; set; }
        public virtual tRegDocContr tRegDocContr { get; set; }
    }
}
