//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRiskMapHoraire
    {
        public int ID { get; set; }
        public int RiskMapID { get; set; }
        public int EnvoiHoraireTypeID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
    
        public virtual tEnvoiHoraireType tEnvoiHoraireType { get; set; }
        public virtual tRiskMap tRiskMap { get; set; }
    }
}
