//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSecurity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSecurity()
        {
            this.tSecuritySecurityGroup = new HashSet<tSecuritySecurityGroup>();
            this.tCoupon = new HashSet<tCoupon>();
            this.tSecurityRate = new HashSet<tSecurityRate>();
            this.tSecurityRate1 = new HashSet<tSecurityRate>();
            this.tSecurityRate2 = new HashSet<tSecurityRate>();
            this.tModDeal = new HashSet<tModDeal>();
            this.tModDeal1 = new HashSet<tModDeal>();
            this.tQuikDeal = new HashSet<tQuikDeal>();
        }
    
        public int SecurityID { get; set; }
        public string Name { get; set; }
        public string ISIN { get; set; }
        public Nullable<int> IssuerID { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<double> Nominal { get; set; }
        public Nullable<int> NominalFundID { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> CouponBasisID { get; set; }
        public Nullable<int> Lot { get; set; }
    
        public virtual tFinInst tFinInst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSecuritySecurityGroup> tSecuritySecurityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCoupon> tCoupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSecurityRate> tSecurityRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSecurityRate> tSecurityRate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSecurityRate> tSecurityRate2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tModDeal> tModDeal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tModDeal> tModDeal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tQuikDeal> tQuikDeal { get; set; }
    }
}
