//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSecurityRate
    {
        public int ID { get; set; }
        public int SecurityID { get; set; }
        public System.DateTime RateDate { get; set; }
        public byte RateType { get; set; }
        public Nullable<double> Course { get; set; }
        public Nullable<double> Coupon { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> PriceFundID { get; set; }
        public Nullable<double> PriceCourse { get; set; }
        public Nullable<double> Nominal { get; set; }
        public Nullable<int> NominalFundID { get; set; }
    
        public virtual tSecurity tSecurity { get; set; }
        public virtual tSecurity tSecurity1 { get; set; }
        public virtual tSecurity tSecurity2 { get; set; }
    }
}
