//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSecuritySecurityGroup
    {
        public int SecurityGroupID { get; set; }
        public int SecurityID { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public int ID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tSecurity tSecurity { get; set; }
        public virtual tSecurityGroup tSecurityGroup { get; set; }
    }
}
