//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTreaty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTreaty()
        {
            this.tPortfolioTreaty = new HashSet<tPortfolioTreaty>();
            this.tModDeal = new HashSet<tModDeal>();
            this.tQuikDeal = new HashSet<tQuikDeal>();
            this.tTreatyCode = new HashSet<tTreatyCode>();
            this.tEnregistrement = new HashSet<tEnregistrement>();
        }
    
        public int TreatyID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FinInstID { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> DateInvest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPortfolioTreaty> tPortfolioTreaty { get; set; }
        public virtual tFinInst tFinInst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tModDeal> tModDeal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tQuikDeal> tQuikDeal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTreatyCode> tTreatyCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEnregistrement> tEnregistrement { get; set; }
    }
}
