//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTreatyCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTreatyCode()
        {
            this.tMyTreatyCode = new HashSet<tMyTreatyCode>();
        }
    
        public int ID { get; set; }
        public int TreatyID { get; set; }
        public string Code { get; set; }
        public string Razdel { get; set; }
        public Nullable<int> Chain { get; set; }
    
        public virtual tTreaty tTreaty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMyTreatyCode> tMyTreatyCode { get; set; }
    }
}
