//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWarrant
    {
        public int ID { get; set; }
        public string Nomer { get; set; }
        public Nullable<System.DateTime> DateB { get; set; }
        public string Principal { get; set; }
        public string Confidant { get; set; }
        public string Place { get; set; }
        public string Functions { get; set; }
        public Nullable<System.DateTime> DateE { get; set; }
        public string Initiator { get; set; }
        public Nullable<System.DateTime> DateCancel { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string UserName { get; set; }
        public string FileName { get; set; }
        public string FileName2 { get; set; }
        public string Comment { get; set; }
    }
}
