#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MO5.Areas.Code.Views.Envoi
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class declViolCourriel : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
            
  public DateTime dt { get; set; }
  public dynamic q { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral(@"
<style>
  table
  {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th
  {
    font-size: .8em;
    font-family: Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span
  {
    font-style: italic;
  }

  th
  {
    font-size: .7em;
  }
</style>
<h3>Нарушения в портфелях клиентов</h3>
<h4>Отчетная дата: ");

            
            #line 33 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
              Write(dt.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n<table>\r\n  <tr>\r\n    <th>Клиент</th>\r\n    <th>Дата возникновения</th>\r\n   " +
" <th>Описание нарушения</th>\r\n    <th>Предельное значение</th>\r\n    <th>Фактичес" +
"кое значение</th>\r\n    <th>Причина</th>\r\n    <th>Срок</th>\r\n  </tr>\r\n");

            
            #line 44 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
   foreach (var qq in q)
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <td>");

            
            #line 47 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
     Write(qq.fiName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 48 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
     Write(qq.DDate.ToString("dd.MM.yy"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 49 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
     Write(qq.Descr);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 50 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
     Write(qq.MaxValue);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 51 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
     Write(qq.Value);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 52 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
     Write(qq.Reason);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 53 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
      Write(qq.TermDate != null ? qq.TermDate.ToString("dd.MM.yy") : "");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 55 "..\..\Areas\Code\Views\Envoi\declViolCourriel.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
