#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MO5;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Code/Views/Envoi/EMail.cshtml")]
    public partial class _Areas_Code_Views_Envoi_EMail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Code_Views_Envoi_EMail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
  
  Layout = "~/Views/Shared/_Layout.cshtml";
  ViewBag.Title = "Список Email";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n  <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .icon-user-add {\r\n      background-image: url(");

            
            #line 8 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
                       Write(Href("~/Scripts/ExtJS62/build/classic/theme-crisp/resources/images/tree/drop-add.gif"));

            
            #line default
            #line hidden
WriteLiteral(") !important;\r\n    }\r\n\r\n    .icon-delete {\r\n      background-image: url(");

            
            #line 12 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
                       Write(Href("~/Content/images/delete.png"));

            
            #line default
            #line hidden
WriteLiteral(") !important;\r\n    }\r\n\r\n    .icon-refresh {\r\n      background-image: url(");

            
            #line 16 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
                       Write(Href("~/Scripts/ExtJS62/build/classic/theme-crisp/resources/images/grid/refresh.png"));

            
            #line default
            #line hidden
WriteLiteral(") !important;\r\n    }\r\n  </style>\r\n  <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 612), Tuple.Create("\"", 692)
, Tuple.Create(Tuple.Create("", 619), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ExtJS62/build/classic/theme-crisp/resources/theme-crisp-all.css")
, 619), false)
);

WriteLiteral(" />\r\n  <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 730), Tuple.Create("\"", 770)
, Tuple.Create(Tuple.Create("", 736), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ExtJS62/ext-bootstrap.js")
, 736), false)
);

WriteLiteral("></script>\r\n  <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

    Ext.define('EMail', {
      extend: 'Ext.data.Model',
      idProperty: 'id',
      fields: ['id', 'name', 'email']
    });

    var store = Ext.create('Ext.data.Store', {
      remoteSort: true,
      model: 'EMail',
      autoLoad: true,
      //autoSync: true,
      proxy: {
        actionMethods: { read: 'POST' },
        type: 'ajax',
        api: {
          create: '");

            
            #line 38 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
              Write(Url.Action("addEMail"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n          update: \'");

            
            #line 39 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
              Write(Url.Action("updEMail"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n          destroy: \'");

            
            #line 40 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
               Write(Url.Action("delEMail"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n          read: \'");

            
            #line 41 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
            Write(Url.Action("getEMailList"));

            
            #line default
            #line hidden
WriteLiteral("\'\r\n        },\r\n        reader: {\r\n          type: \'json\',\r\n          successPrope" +
"rty: \'success\',\r\n          root: \'data\',\r\n          messageProperty: \'message\'\r\n" +
"        },\r\n        writer: {\r\n          type: \'json\',\r\n          root: \'data\',\r" +
"\n          writeAllFields: true,\r\n          allowSingle: false,\r\n          encod" +
"e: false\r\n        },\r\n        listeners: {\r\n          exception: function (proxy" +
", response, operation) {\r\n            alert(operation.getError());\r\n          }\r" +
"\n        },\r\n        simpleSortMode: true\r\n      }\r\n    });\r\n\r\n    Ext.define(\'E" +
"M.Win\', {\r\n      extend: \'Ext.window.Window\',\r\n      alias: \'widget.emwin\',\r\n\r\n " +
"     initComponent: function () {\r\n        //this.addEvents(\'create\');\r\n        " +
"//this.addEvents(\'update\');\r\n        Ext.apply(this, {\r\n          activeRecord: " +
"null,\r\n          title: \'Добавить\',\r\n          width: 450,\r\n          autoHeight" +
": true,\r\n          closeAction: \'hide\',\r\n          modal: true,\r\n          layou" +
"t: \'fit\',\r\n          plain: true,\r\n          bodyStyle: \'padding:5px;\',\r\n       " +
"   buttonAlign: \'center\',\r\n          border: true,\r\n          items: {\r\n        " +
"    xtype: \'panel\',\r\n            border: true,\r\n            autoHeight: true,\r\n " +
"           baseCls: \'x-plain\',\r\n            items: [{\r\n              xtype: \'for" +
"m\',\r\n              autoHeight: true,\r\n              border: true,\r\n             " +
" baseCls: \'x-plain\',\r\n              bodyPadding: 5,\r\n              fieldDefaults" +
": { labelWidth: 70, labelAlign: \'right\' },\r\n              defaults: { anchor: \'1" +
"00%\' },\r\n              items: [{\r\n                xtype: \'fieldcontainer\',\r\n    " +
"            layout: \'hbox\',\r\n                items: [{\r\n                  xtype:" +
" \'textfield\',\r\n                  name: \'email\',\r\n                  flex: 1,\r\n   " +
"               fieldLabel: \'EMail\',\r\n                  vtype: \'email\',\r\n        " +
"          allowBlank: false,\r\n                  blankText: \'Введите EMail\',\r\n   " +
"               emptyText: \'Введите EMail\',\r\n                  msgTarget: \'side\'," +
"\r\n                  margin: \'0 5 0 0\'\r\n                }, {\r\n                  x" +
"type: \'button\',\r\n                  text: \'Найти\',\r\n                  handler: th" +
"is.onFind\r\n                }]\r\n              }, {\r\n                xtype: \'textf" +
"ield\',\r\n                name: \'name\',\r\n                fieldLabel: \'Имя\',\r\n     " +
"           allowBlank: false,\r\n                blankText: \'Введите имя\',\r\n      " +
"          emptyText: \'Введите имя\',\r\n                msgTarget: \'side\'\r\n        " +
"      }]\r\n            }]\r\n          },\r\n          buttons: [{\r\n            itemI" +
"d: \'save\',\r\n            text: \'Сохранить\',\r\n            scope: this,\r\n          " +
"  handler: this.onSave\r\n          }, {\r\n            text: \'Отмена\',\r\n           " +
" scope: this,\r\n            handler: function () {\r\n              this.hide();\r\n " +
"           }\r\n          }]\r\n        });\r\n        this.callParent();\r\n      },\r\n\r" +
"\n      setActiveRecord: function (record) {\r\n        this.activeRecord = record;" +
"\r\n        this.down(\'form\').getForm().reset();\r\n        if (record) {\r\n         " +
" this.down(\'#save\').enable();\r\n          this.down(\'form\').getForm().loadRecord(" +
"record);\r\n        } else {\r\n          this.down(\'#save\').disable();\r\n        }\r\n" +
"      },\r\n\r\n      onFind: function () {\r\n        var me = this;\r\n        Ext.Aja" +
"x.request({\r\n          url: \'");

            
            #line 157 "..\..\Areas\Code\Views\Envoi\EMail.cshtml"
           Write(Url.Action("findADInfo"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n          timeout: 60000,\r\n          params: {\r\n            email: me.up(\'for" +
"m\').getForm().getValues().email\r\n          },\r\n          success: function (resp" +
"onse) {\r\n            var jr = Ext.decode(response.responseText);\r\n            if" +
" (jr.success == true)\r\n              me.up(\'form\').getForm().findField(\'name\').s" +
"etValue(Ext.decode(response.responseText).name);\r\n            else\r\n            " +
"  alert(\'Email не найден!\')\r\n          },\r\n          scope: this,\r\n          fai" +
"lure: function (response) {\r\n            alert(\'Ошибка!\');\r\n          }\r\n       " +
" });\r\n\r\n      },\r\n\r\n      onSave: function () {\r\n        var active = this.activ" +
"eRecord, form = this.down(\'form\').getForm();\r\n        if (!active) {\r\n          " +
"return;\r\n        }\r\n        if (form.isValid()) {\r\n          if (this.title == \'" +
"Добавить\')\r\n            this.fireEvent(\'create\', this, form.getValues(false, fal" +
"se, false, true));\r\n          else {\r\n            form.updateRecord(active);\r\n  " +
"          this.fireEvent(\'update\');\r\n          }\r\n          this.hide();\r\n      " +
"  }\r\n      }\r\n\r\n    });\r\n\r\n    Ext.define(\'EM.Grid\', {\r\n      extend: \'Ext.grid." +
"Panel\',\r\n      alias: \'widget.emgrid\',\r\n      wini: null,\r\n      initComponent: " +
"function () {\r\n        Ext.apply(this, {\r\n          height: 700,\r\n          titl" +
"e: \'EMail\',\r\n          store: store,\r\n          columnLines: true,\r\n          co" +
"lumns: [/*{\r\n              xtype: \'rownumberer\',\r\n              width: 30,\r\n    " +
"          sortable: false\r\n            },*/ {\r\n              header: \"Имя\",\r\n   " +
"           dataIndex: \'name\',\r\n              width: 240,\r\n              sortable" +
": true\r\n            }, {\r\n              header: \"EMail\",\r\n              dataInde" +
"x: \'email\',\r\n              flex: 1,\r\n              sortable: true\r\n            }" +
"],\r\n          viewConfig: {\r\n            enableTextSelection: true,\r\n           " +
" loadMask: false,\r\n            animate: false,\r\n            trackOver: true,\r\n  " +
"          stripeRows: true\r\n          },\r\n          dockedItems: [{\r\n           " +
" xtype: \'toolbar\',\r\n            items: [{\r\n              iconCls: \'icon-user-add" +
"\',\r\n              text: \'Добавить\',\r\n              scope: this,\r\n              h" +
"andler: this.onAddClick\r\n\r\n            }, {\r\n              text: \'Изменить\',\r\n  " +
"            disabled: true,\r\n              itemId: \'change\',\r\n              scop" +
"e: this,\r\n              handler: this.onChangeClick\r\n            }, {\r\n         " +
"     iconCls: \'icon-delete\',\r\n              text: \'Удалить\',\r\n              disa" +
"bled: true,\r\n              itemId: \'delete\',\r\n              scope: this,\r\n      " +
"        handler: this.onDeleteClick\r\n            }, {\r\n              iconCls: \'i" +
"con-refresh\',\r\n              scope: this,\r\n              text: \'Обновить\',\r\n    " +
"          handler: function () { store.load(); }\r\n            }");

WriteLiteral("]\r\n          }]\r\n        });\r\n        this.callParent();\r\n        this.getSelecti" +
"onModel().on(\'selectionchange\', this.onSelectChange, this);\r\n        this.on(\'it" +
"emdblclick\', this.onRowDblClick, this);\r\n      },\r\n\r\n      onAddClick: function " +
"() {\r\n        var rec = new EMail({ name: \'\', email: \'\' });\r\n        if (!this.w" +
"ini) {\r\n          this.onCreateWin();\r\n        }\r\n        this.wini.setTitle(\'До" +
"бавить\');\r\n        this.wini.setActiveRecord(rec);\r\n        this.wini.show(this)" +
";\r\n      },\r\n\r\n      onChangeClick: function () {\r\n        if (!this.wini) {\r\n  " +
"        this.onCreateWin();\r\n        }\r\n        this.wini.setTitle(\'Изменить\');\r" +
"\n        this.wini.setActiveRecord(this.getSelectionModel().getSelection()[0]);\r" +
"\n        this.wini.show(this);\r\n      },\r\n\r\n      onRowDblClick: function () {\r\n" +
"        this.onChangeClick();\r\n      },\r\n\r\n      onCreateWin: function () {\r\n   " +
"     this.wini = Ext.create(\'EM.Win\', {\r\n          scope: this,\r\n          liste" +
"ners: {\r\n            scope: this,\r\n            create: function (form, data) {\r\n" +
"              this.store.insert(0, data);\r\n              this.store.sync();\r\n   " +
"         },\r\n            update: function () {\r\n              this.store.sync();" +
"\r\n            }\r\n          }\r\n        });\r\n      },\r\n\r\n      onDeleteClick: func" +
"tion () {\r\n        var selection = this.getView().getSelectionModel().getSelecti" +
"on()[0];\r\n        if (selection) {\r\n          if (window.confirm(\'Удалить стр.?\'" +
")) {\r\n            this.store.remove(selection);\r\n            this.store.sync();\r" +
"\n          }\r\n        }\r\n      },\r\n\r\n      onSelectChange: function (selModel, s" +
"elections) {\r\n        this.down(\'#delete\').setDisabled(selections.length === 0);" +
"\r\n        this.down(\'#change\').setDisabled(selections.length === 0);\r\n      }\r\n\r" +
"\n    });\r\n\r\n    Ext.onReady(function () {\r\n\r\n      Ext.tip.QuickTipManager.init(" +
");\r\n      var grid = Ext.create(\'EM.Grid\', {\r\n        id: \'grid-panel\',\r\n       " +
" renderTo: \'grid\'\r\n      });\r\n\r\n    });\r\n  </script>\r\n");

});

WriteLiteral("<div");

WriteLiteral(" id=\"grid\"");

WriteLiteral(" style=\"padding: 30px\"");

WriteLiteral(">\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
