#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MO5;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Code/Views/Envoi/riskMapCourriel.cshtml")]
    public partial class _Areas_Code_Views_Envoi_riskMapCourriel_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Code_Views_Envoi_riskMapCourriel_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
  
  Layout = null;

            
            #line default
            #line hidden
WriteLiteral(@"

<style>
  table {
    border-collapse: collapse;
    border: 1px solid gray;
  }

  td, span, th {
    font-size: .8em;
    font-family: Verdana, Helvetica, Sans-Serif;
    text-align: left;
  }

  span {
    font-style: italic;
  }

  th {
    font-size: .7em;
  }
</style>
<h4>Дирекция риск-менеджмента обращает внимание на необходимость соблюдения следующих операционных контролей</h4>
<table");

WriteLiteral(" border=\"1\"");

WriteLiteral(" style=\"border: 1px solid #262626;\"");

WriteLiteral(">\r\n  <tr>\r\n    <th>Структурное подразделение</th>\r\n    <th>Бизнес процесс</th>\r\n " +
"   ");

WriteLiteral("\r\n    <th>Риск наименование</th>\r\n    ");

WriteLiteral("\r\n    <th>");

            
            #line 39 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
    Write(ViewBag.i == 0 ? "Цель" : "Контроль");

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
Write(Html.Raw(ViewBag.i == 0 ? "<th>Владелец цели</th>" : ""));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <th>Владелец контроля</th>\r\n  </tr>\r\n");

            
            #line 43 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
  
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
   foreach (var qq in Model)
  {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n      <td>");

            
            #line 46 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.Dep);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      <td>");

            
            #line 47 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.BisProc);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      ");

WriteLiteral("\r\n      <td>");

            
            #line 49 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.RiskName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n      ");

WriteLiteral("\r\n      <td>");

            
            #line 56 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.c1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

WriteLiteral("      ");

            
            #line 57 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
 Write(Html.Raw(ViewBag.i == 0 ? "<td>" + @qq.PossesseurBut + "</td>" : ""));

            
            #line default
            #line hidden
WriteLiteral("\r\n      <td>");

            
            #line 58 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
     Write(qq.PossesseurControl);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");

            
            #line 60 "..\..\Areas\Code\Views\Envoi\riskMapCourriel.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<br>\r\n<span>Дирекция риск-менеджмента</span>\r\n");

        }
    }
}
#pragma warning restore 1591
